[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_token = "GUGGHzwC8wEKY3g7QS38YmoS8t5Q2faWAGAfxDK2bXbb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "artifacts/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
